{% set name = "Orange3-Prototypes" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c25b2027ddd005f8f48514cc6d9e6096adfa7fd38a1210ca1d4876fead4fb69

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - Orange3 >=3.28
    - numpy
    - scipy
    - scikit-learn
    - pyqtgraph
    - AnyQt >=0.0.8
    - pandas

test:
  imports:
    - orangecontrib.prototypes

about:
  home: https://orangedatamining.com/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Addon with widgets which are still prototypes
  description: |
    Addon with widgets which are still prototypes. Only for the brave.
  doc_url: https://readthedocs.org/projects/orange3-prototypes/
  dev_url: https://github.com/biolab/orange3-prototypes

extra:
  recipe-maintainers:
    - primozgodec
    - markotoplak
    - ajdapretnar
